directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV2_AWS_57 #"Ensure Secrets Manager secrets should have automatic rotation enabled"